#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header
# Add HAProxy PPA
apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.5
apt-get update
apt-get install -y haproxy

echo "ENABLED=1" >> /etc/default/haproxy
mv /etc/haproxy/haproxy.cfg{,.original}
touch /etc/haproxy/haproxy.cfg

# Write HAProxy configuration to the new file
printf %s "global
  log 127.0.0.1 local0 notice
  maxconn 2000
  user haproxy
  group haproxy
defaults
  log   global
  mode  http
  option httplog
  option dontlognull
  retries 3
  open redispatch
  timeout connect 5000
  timeout client 10000
  timeout server 10000
listen my_custom_listener
  bind 0.0.0.0:80
  mode http
  stats enable
  stats uri/haproxy?stats
  balance roundrobin
  option httpclose
  option forwardfor
  server 310219-web-01 54.87.242.202:80 check
  server 310219-web-02 100.26.212.66:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start

